# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ubuntu/mini

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ubuntu/mini

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/mini/CMakeFiles /home/ubuntu/mini/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/mini/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mini

# Build rule for target.
mini: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mini
.PHONY : mini

# fast build rule for target.
mini/fast:
	$(MAKE) -f CMakeFiles/mini.dir/build.make CMakeFiles/mini.dir/build
.PHONY : mini/fast

Buffer.o: Buffer.cpp.o

.PHONY : Buffer.o

# target to build an object file
Buffer.cpp.o:
	$(MAKE) -f CMakeFiles/mini.dir/build.make CMakeFiles/mini.dir/Buffer.cpp.o
.PHONY : Buffer.cpp.o

Buffer.i: Buffer.cpp.i

.PHONY : Buffer.i

# target to preprocess a source file
Buffer.cpp.i:
	$(MAKE) -f CMakeFiles/mini.dir/build.make CMakeFiles/mini.dir/Buffer.cpp.i
.PHONY : Buffer.cpp.i

Buffer.s: Buffer.cpp.s

.PHONY : Buffer.s

# target to generate assembly for a file
Buffer.cpp.s:
	$(MAKE) -f CMakeFiles/mini.dir/build.make CMakeFiles/mini.dir/Buffer.cpp.s
.PHONY : Buffer.cpp.s

DBOperation.o: DBOperation.cpp.o

.PHONY : DBOperation.o

# target to build an object file
DBOperation.cpp.o:
	$(MAKE) -f CMakeFiles/mini.dir/build.make CMakeFiles/mini.dir/DBOperation.cpp.o
.PHONY : DBOperation.cpp.o

DBOperation.i: DBOperation.cpp.i

.PHONY : DBOperation.i

# target to preprocess a source file
DBOperation.cpp.i:
	$(MAKE) -f CMakeFiles/mini.dir/build.make CMakeFiles/mini.dir/DBOperation.cpp.i
.PHONY : DBOperation.cpp.i

DBOperation.s: DBOperation.cpp.s

.PHONY : DBOperation.s

# target to generate assembly for a file
DBOperation.cpp.s:
	$(MAKE) -f CMakeFiles/mini.dir/build.make CMakeFiles/mini.dir/DBOperation.cpp.s
.PHONY : DBOperation.cpp.s

Manager.o: Manager.cpp.o

.PHONY : Manager.o

# target to build an object file
Manager.cpp.o:
	$(MAKE) -f CMakeFiles/mini.dir/build.make CMakeFiles/mini.dir/Manager.cpp.o
.PHONY : Manager.cpp.o

Manager.i: Manager.cpp.i

.PHONY : Manager.i

# target to preprocess a source file
Manager.cpp.i:
	$(MAKE) -f CMakeFiles/mini.dir/build.make CMakeFiles/mini.dir/Manager.cpp.i
.PHONY : Manager.cpp.i

Manager.s: Manager.cpp.s

.PHONY : Manager.s

# target to generate assembly for a file
Manager.cpp.s:
	$(MAKE) -f CMakeFiles/mini.dir/build.make CMakeFiles/mini.dir/Manager.cpp.s
.PHONY : Manager.cpp.s

MiniServer.o: MiniServer.cpp.o

.PHONY : MiniServer.o

# target to build an object file
MiniServer.cpp.o:
	$(MAKE) -f CMakeFiles/mini.dir/build.make CMakeFiles/mini.dir/MiniServer.cpp.o
.PHONY : MiniServer.cpp.o

MiniServer.i: MiniServer.cpp.i

.PHONY : MiniServer.i

# target to preprocess a source file
MiniServer.cpp.i:
	$(MAKE) -f CMakeFiles/mini.dir/build.make CMakeFiles/mini.dir/MiniServer.cpp.i
.PHONY : MiniServer.cpp.i

MiniServer.s: MiniServer.cpp.s

.PHONY : MiniServer.s

# target to generate assembly for a file
MiniServer.cpp.s:
	$(MAKE) -f CMakeFiles/mini.dir/build.make CMakeFiles/mini.dir/MiniServer.cpp.s
.PHONY : MiniServer.cpp.s

MySql.o: MySql.cpp.o

.PHONY : MySql.o

# target to build an object file
MySql.cpp.o:
	$(MAKE) -f CMakeFiles/mini.dir/build.make CMakeFiles/mini.dir/MySql.cpp.o
.PHONY : MySql.cpp.o

MySql.i: MySql.cpp.i

.PHONY : MySql.i

# target to preprocess a source file
MySql.cpp.i:
	$(MAKE) -f CMakeFiles/mini.dir/build.make CMakeFiles/mini.dir/MySql.cpp.i
.PHONY : MySql.cpp.i

MySql.s: MySql.cpp.s

.PHONY : MySql.s

# target to generate assembly for a file
MySql.cpp.s:
	$(MAKE) -f CMakeFiles/mini.dir/build.make CMakeFiles/mini.dir/MySql.cpp.s
.PHONY : MySql.cpp.s

TcpConnection.o: TcpConnection.cpp.o

.PHONY : TcpConnection.o

# target to build an object file
TcpConnection.cpp.o:
	$(MAKE) -f CMakeFiles/mini.dir/build.make CMakeFiles/mini.dir/TcpConnection.cpp.o
.PHONY : TcpConnection.cpp.o

TcpConnection.i: TcpConnection.cpp.i

.PHONY : TcpConnection.i

# target to preprocess a source file
TcpConnection.cpp.i:
	$(MAKE) -f CMakeFiles/mini.dir/build.make CMakeFiles/mini.dir/TcpConnection.cpp.i
.PHONY : TcpConnection.cpp.i

TcpConnection.s: TcpConnection.cpp.s

.PHONY : TcpConnection.s

# target to generate assembly for a file
TcpConnection.cpp.s:
	$(MAKE) -f CMakeFiles/mini.dir/build.make CMakeFiles/mini.dir/TcpConnection.cpp.s
.PHONY : TcpConnection.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/mini.dir/build.make CMakeFiles/mini.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/mini.dir/build.make CMakeFiles/mini.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/mini.dir/build.make CMakeFiles/mini.dir/main.cpp.s
.PHONY : main.cpp.s

reply.o: reply.cpp.o

.PHONY : reply.o

# target to build an object file
reply.cpp.o:
	$(MAKE) -f CMakeFiles/mini.dir/build.make CMakeFiles/mini.dir/reply.cpp.o
.PHONY : reply.cpp.o

reply.i: reply.cpp.i

.PHONY : reply.i

# target to preprocess a source file
reply.cpp.i:
	$(MAKE) -f CMakeFiles/mini.dir/build.make CMakeFiles/mini.dir/reply.cpp.i
.PHONY : reply.cpp.i

reply.s: reply.cpp.s

.PHONY : reply.s

# target to generate assembly for a file
reply.cpp.s:
	$(MAKE) -f CMakeFiles/mini.dir/build.make CMakeFiles/mini.dir/reply.cpp.s
.PHONY : reply.cpp.s

request_parser.o: request_parser.cpp.o

.PHONY : request_parser.o

# target to build an object file
request_parser.cpp.o:
	$(MAKE) -f CMakeFiles/mini.dir/build.make CMakeFiles/mini.dir/request_parser.cpp.o
.PHONY : request_parser.cpp.o

request_parser.i: request_parser.cpp.i

.PHONY : request_parser.i

# target to preprocess a source file
request_parser.cpp.i:
	$(MAKE) -f CMakeFiles/mini.dir/build.make CMakeFiles/mini.dir/request_parser.cpp.i
.PHONY : request_parser.cpp.i

request_parser.s: request_parser.cpp.s

.PHONY : request_parser.s

# target to generate assembly for a file
request_parser.cpp.s:
	$(MAKE) -f CMakeFiles/mini.dir/build.make CMakeFiles/mini.dir/request_parser.cpp.s
.PHONY : request_parser.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... mini"
	@echo "... Buffer.o"
	@echo "... Buffer.i"
	@echo "... Buffer.s"
	@echo "... DBOperation.o"
	@echo "... DBOperation.i"
	@echo "... DBOperation.s"
	@echo "... Manager.o"
	@echo "... Manager.i"
	@echo "... Manager.s"
	@echo "... MiniServer.o"
	@echo "... MiniServer.i"
	@echo "... MiniServer.s"
	@echo "... MySql.o"
	@echo "... MySql.i"
	@echo "... MySql.s"
	@echo "... TcpConnection.o"
	@echo "... TcpConnection.i"
	@echo "... TcpConnection.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... reply.o"
	@echo "... reply.i"
	@echo "... reply.s"
	@echo "... request_parser.o"
	@echo "... request_parser.i"
	@echo "... request_parser.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

